[project]
name = "compressdata"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "torch>=2.0.0",
    "tqdm>=4.67.1",
    "wandb>=0.24.0",
]
